"""Initial migration

Revision ID: 75c62aa75a78
Revises: 
Create Date: 2026-07-12 12:40:02.495807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75c62aa75a78'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_number', sa.String(length=100), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.Enum('pdf', 'docx', 'txt', name='filetype'), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('status', sa.Enum('uploaded', 'text_extracted', 'entities_extracted', 'indexed', 'ready_for_investigation', 'failed', name='fir_status'), server_default='uploaded', nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_path')
    )
    op.create_index(op.f('ix_firs_case_number'), 'firs', ['case_number'], unique=False)
    op.create_table('fir_document_contents',
    sa.Column('fir_id', sa.UUID(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('character_count', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('extraction_status', sa.String(length=50), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fir_id'], ['firs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fir_document_contents_fir_id'), 'fir_document_contents', ['fir_id'], unique=True)
    op.create_table('fir_embeddings',
    sa.Column('fir_id', sa.UUID(), nullable=False),
    sa.Column('qdrant_point_id', sa.String(length=100), nullable=False),
    sa.Column('embedding_model', sa.String(length=150), nullable=False),
    sa.Column('vector_dimension', sa.Integer(), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['fir_id'], ['firs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fir_embeddings_fir_id'), 'fir_embeddings', ['fir_id'], unique=True)
    op.create_table('fir_entities',
    sa.Column('fir_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_value', sa.String(length=500), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fir_id'], ['firs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fir_entities_entity_type'), 'fir_entities', ['entity_type'], unique=False)
    op.create_index(op.f('ix_fir_entities_fir_id'), 'fir_entities', ['fir_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fir_entities_fir_id'), table_name='fir_entities')
    op.drop_index(op.f('ix_fir_entities_entity_type'), table_name='fir_entities')
    op.drop_table('fir_entities')
    op.drop_index(op.f('ix_fir_embeddings_fir_id'), table_name='fir_embeddings')
    op.drop_table('fir_embeddings')
    op.drop_index(op.f('ix_fir_document_contents_fir_id'), table_name='fir_document_contents')
    op.drop_table('fir_document_contents')
    op.drop_index(op.f('ix_firs_case_number'), table_name='firs')
    op.drop_table('firs')
    # ### end Alembic commands ###
